### ISSUE TITLE
How to make this model work for 24k/48kHz sampling rates?

### ISSUE THREAD

**Issue by skol101** [OlaWod/FreeVC#14]
Is only thing required is retraining WavLM to the respective sampling rates?

**Comment by OlaWod** [comment]
I've updated tips [here](https://github.com/OlaWod/FreeVC/tree/main/tips-for-synthesizing-24KHz-wavs-from-16kHz-wavs).

**Comment by skol101** [comment]
Cheers. Is there a way to train on 24kHz dataset, or it wouldn't make much difference ?

**Comment by OlaWod** [comment]
Yes. Just follow the training example [here](https://github.com/OlaWod/FreeVC/tree/main/tips-for-synthesizing-24KHz-wavs-from-16kHz-wavs#training-example).

**Comment by skol101** [comment]
Thank you!
