### ISSUE TITLE
SR based augmentation execution

### ISSUE THREAD

**Issue by skol101** [OlaWod/FreeVC#15]
Hello,

There's a list of commands lines -- can they be run in parallel on separate GPUs  or they must be run in this order?

# run these if you want to train with SR-based augmentation
CUDA_VISIBLE_DEVICES=1 python preprocess_sr.py --min 68 --max 72
CUDA_VISIBLE_DEVICES=1 python preprocess_sr.py --min 73 --max 76
CUDA_VISIBLE_DEVICES=2 python preprocess_sr.py --min 77 --max 80
CUDA_VISIBLE_DEVICES=2 python preprocess_sr.py --min 81 --max 84
CUDA_VISIBLE_DEVICES=3 python preprocess_sr.py --min 85 --max 88
CUDA_VISIBLE_DEVICES=3 python preprocess_sr.py --min 89 --max 92

**Comment by skol101** [comment]
I got, they can be run in parallel ^)

**Comment by skol101** [comment]
This process is very disk hungry -- full VCTK dataset after processing takes about 350Gb.

**Comment by OlaWod** [comment]
yes. or you can modify `data_utils.py` to make it process on the fly instead of loading from disk, so that it doesn't need much disk space.
