### ISSUE TITLE
Vocoder isn't used in interefernce?

### ISSUE THREAD

**Issue by skol101** [OlaWod/FreeVC#17]
Looking at convert.py I don't see that vocoder is used to get waveform , correct?

**Comment by OlaWod** [comment]
yes. it does not need an additional vocoder for inference. the decoder serves the role of vocoder.

**Comment by skol101** [comment]
I wonder if a different Hifigan-like vocoder (like Ada https://github.com/yuan1615/AdaVocoder ) can be used ?

**Comment by OlaWod** [comment]
yes

**Comment by skol101** [comment]
I'll try switch from hifigan to adavcoder, and copying models.py from that model. As I understand it's only used in prepare_sr step. 

Also, in another issue I saw that the pre-trained model can be fine tuned on a custom dataset, so it's not required to actually train everything from scratch.

**Comment by OlaWod** [comment]
yes you can do.
