### ISSUE TITLE
Question about target speaker reproduction/transfer

### ISSUE THREAD

**Issue by space-pope** [OlaWod/FreeVC#18]
About how long into training did the voice conversion effect start to be noticeable for you?

I ask because so far in my experiments training from scratch, audio reproduction for the source speaker seems to be pretty good, but passing a different speaker as the conversion target doesn't change the voice much. It did work better when I fine-tuned your pretrained model on my dataset, so I'm wondering how long I should let new experiments run before I deem them failures.

**Comment by OlaWod** [comment]
it depends. for vctk 300k steps are enough.

**Comment by space-pope** [comment]
Gotcha—thanks for the response!

**Comment by yt605155624** [comment]
@space-pope hi, I wonder how big your new dataset is, how many `epoch` or `iters` (and the `batch_size` is?) have you fintuned till get good results?
