### ISSUE TITLE
Some observations after 290k steps

### ISSUE THREAD

**Issue by skol101** [OlaWod/FreeVC#20]
Hello,

After training for 290k (and still going) on 2 GPUs, I have decided to test conversion. 

Results so far:
 
-- Conversion to M seen (but not seen in HifiGan):
1. F seen to M seen -- very similar to the src F seen
2. M seen to M seen -- very similar to the src M seen
3. F unseen to M seen -- very similar to the src F seen
4. M unseen to M seen -- pretty similar to the tgt M seen 

So, 4 is pretty good, whilst 1-3 are similar to the source, not the target.

My setup is the same as yours, used Freevc with SR pre training. 

Dataset has 110 VCTK speakers in total (including 40 custom speakers). 

Is this the question of more training? Or HifiGan not trained on custom speakers? 

UPDATE:
-- Conversion to M seen (also seen in HifiGan):
1. F unseen to M seen -- pretty similar to the tgt M seen
2. M unseen to M seen -- pretty similar to the tgt M seen

So, it seems like the issue is with Vocoder -- it must be trained on all dataset beforehand.

**Comment by skol101** [comment]
Btw, eval section of the tensorboard shows nothing.

**Comment by OlaWod** [comment]
Tested on my 290k checkpoint and it can convert properly. I guess your problem might be caused by dataset imbalance (i.e. data of some tgt speakers are too little compared to other speakers).
Eval section of the tensorboard is not empty. Maybe you did not tick on '<log_dir>/eval' on the bottom left corner of tensorboard.

**Comment by skol101** [comment]
Indeed my custom dataset has fewer total time per speaker (about 600-700 seconds) than VCTK speakers. But why male to male conversion works OK for the custom speakers.

I guess I have to level out the data for all speakers.

**Comment by OlaWod** [comment]
No idea. (＠_＠;)

**Comment by skol101** [comment]
I don't think this is the case -- as in the original VCTK you have speakers ranging from 600 seconds to 1000 seconds. I'll try with the vocoder trained on the joint dataset and see whether this is the actual reason why conversion isn't consistent for additional speakers.

**Comment by skol101** [comment]
I did click on <log_dir>/eval.

g/ losses are all empty for eval
 
![Screenshot from 2022-12-30 13-41-44](https://user-images.githubusercontent.com/53978091/210066647-709d0836-28a8-4950-b4f3-58e82320fb3c.png)

**Comment by yt605155624** [comment]
> Btw, eval section of the tensorboard shows nothing. Is this expected?

@skol101 , You did haven't wrote eval loss to tensorboard in train.py
