### ISSUE TITLE
Could you also share the discriminator of freevc-24 model?

### ISSUE THREAD

**Issue by lsw5835** [OlaWod/FreeVC#28]
Thanks for amazing work!
I'm doing custom datasets' fine tuning with your model.

Could you also share the discriminator of freevc-24 model?

Thanks!

**Comment by lsw5835** [comment]
Thanks for updates.
If possible, can you also share the code for the 24k changed before uploading the model?

**Comment by OlaWod** [comment]
oh yes. updated.

**Comment by steven850** [comment]
So you didn't train this 24khz model from scratch? you took the 900k step 16khz model and resumed training using the 24khz setting?  
how many steps did you add to the model?

**Comment by OlaWod** [comment]
yes.
the current provided checkpoint is tuned up to 1470k steps (tune 570k steps after loading the 900k model).

**Comment by lsw5835** [comment]
Thanks very much for replying. How long will it take to upload a new model which uses new data utils code?

**Comment by OlaWod** [comment]
Tomorrow night when I'm back home I'll upload it.

**Comment by lsw5835** [comment]
Thanks very much!
