### ISSUE TITLE
Data_utils.py changes

### ISSUE THREAD

**Issue by steven850** [OlaWod/FreeVC#35]
Since you made the changes to the data_utils the other day I am noticing that it seems to be training on much shorter segments. 

the eval audios are also all below 1 second long, most of them just 40 frames. also noticing some obvious gaps/blurs in the generated/GT mels. Can see the "Blurry spots" in these generated mels. where the formants just disappear. 

![genvGT david](https://user-images.githubusercontent.com/43098060/212410751-1a517c7d-a6e1-4543-a227-c08db8f20df1.PNG)
![genvGT david 2](https://user-images.githubusercontent.com/43098060/212410756-4fcc7f4b-3262-4bc0-b97b-b70ddf8099c3.PNG)

**Comment by OlaWod** [comment]
as training goes by the synthesis ability of the model will improve and the synthesized mels will have less over-smoothness problem. 100k steps (batchsize 64) is still in an early training stage.
