### ISSUE TITLE
Changing the dimension of speaker embeddings

### ISSUE THREAD

**Issue by mc-marcocheng** [OlaWod/FreeVC#42]
I tried to swap out the speaker encoder with another one. Each utterance will be encoded into a vector of shape (512,). I tried to change `"gin_channels": 256` into `"gin_channels": 512` in the config of `freevc.json`. Training the model from scratch results in `nan` values in the log: `[nan, nan, nan, nan, nan, 200, 0.0002]`. Do I have to change anything else in the code?

**Comment by OlaWod** [comment]
I don't think it needs other changes. Maybe there's something wrong somewhere else.

**Comment by mc-marcocheng** [comment]
I find out that my speaker encoder is producing `nan`s for utterances that are too short. Now I have fixed the issue.
