### ISSUE TITLE
About Speaker Embeddings

### ISSUE THREAD

**Issue by Shmuel-Gruel** [OlaWod/FreeVC#44]
Hello again, I notice that for training, if using the pretrained speaker encoder and SR, the same speaker embedding is used regardless of the SR augmentation.
(edit: also the audio file and spectrogram are the same, regardless of SR)
I just wanted to double check if this is by design?

Thanks so much for helping everyone :)

**Comment by Shmuel-Gruel** [comment]
Excellent, thank you.
One more question, are the test.txt files used anywhere?

**Comment by OlaWod** [comment]
nowhere.

**Comment by Shmuel-Gruel** [comment]
Understood! Thank you for your insight
