### ISSUE TITLE
48k voice conversion

### ISSUE THREAD

**Issue by lsw5835** [OlaWod/FreeVC#45]
Which one is the best way to generate 48K speech?
(1) Train 90k steps using the 16k dataset, then train 48k using (960 hop_length)
(2) After generating 24k speech, use a super-resolution model for 48k speech conversion.

I really appreciate about your kindly reply. Thanks very much.

**Comment by OlaWod** [comment]
I haven't tried, so I'm not sure.

**Comment by steven850** [comment]
@lsw5835  please keep us updated on 48khz testing. im also curious as to the best approach.
