### ISSUE TITLE
Training Log for 24khz

### ISSUE THREAD

**Issue by steven850** [OlaWod/FreeVC#47]
could you post the tensor board logs for the new 24khz training run if you still have them?

**Comment by OlaWod** [comment]
sure.
![IMG_2119](https://user-images.githubusercontent.com/32514635/215267571-0f36a84e-4b69-4bfa-939a-85870e9d5226.PNG)
![IMG_2120](https://user-images.githubusercontent.com/32514635/215267577-38015250-8997-4d27-81b9-5868439ed466.PNG)
![IMG_2121(20230128-205612)](https://user-images.githubusercontent.com/32514635/215267582-ad29cfe2-f920-44f7-abe8-67834f5bc495.PNG)
training process: load the pretrained 16k checkpoint, train on 24k wavs to 1640k steps, found that these '24k wavs' were upsampled from 22k wavs, repreprocess wavs to real 24k, continue train on real 24k wavs to 2270k steps.

**Comment by steven850** [comment]
Thank you for posting. 
its interesting that the mel loss increased so much between the upsampled and real 24khz files.

**Comment by steven850** [comment]
Trying to make sense of the checkpoints at the moment. 
looking in onedrive, I see Freevc-24, then a folder called duplicated, with files that show a much lower step count then what you said. D_1410000.pth 
which of these files is now the 2270k step?

**Comment by OlaWod** [comment]
> Trying to make sense of the checkpoints at the moment. looking in onedrive, I see Freevc-24, then a folder called duplicated, with files that show a much lower step count then what you said. D_1410000.pth which of these files is now the 2270k step?

the one outside 'duplicated' folder. freevc-24.pth.
