### ISSUE TITLE
SR questions

### ISSUE THREAD

**Issue by steven850** [OlaWod/FreeVC#52]
How did you arrive at plus 12 and minus 12 mels?  Was this just just a random choice or did you test 3,6, 20 etc to find the optimal range?  

Why did you choose to convert to mels, and then resize, and vocode back to wav? Why not just process the audio file and change the pitch? 

you had mentioned in another post that you had gotten better results with a custom trained vocoder, but retrained with the standard VCTK for compatibility with other models. Could you share your custom trained vocoder model? 

Thanks,
Steven

**Comment by OlaWod** [comment]
1. kind of random. just a number that is neither too small nor too large.
2. the main reason is that the implementation is easier and theory is simpler and does not require complicated signal processing knowledge. and i personally think it sounds better than dsp ways.
3. that 'better' is very trivial and i'm a bit lazy to search that vocoder, it's just a normal hifigan trained with 16k VCTK.

**Comment by steven850** [comment]
Ahh ok.
Yeah no problem, no need to look for it. 
Thank you for always replying to all of the questions!
