### ISSUE TITLE
Model Resolution

### ISSUE THREAD

**Issue by steven850** [OlaWod/FreeVC#54]
If I wanted to double the "resolution" of the model, would I just double all of the model parameters? Or do certain parts need to stay a certain size to maintain the information bottleneck? What would be the ideal parameters for a "higher res" model? 

Under train in the config file, What is C_mel and C_Kl?

**Comment by OlaWod** [comment]
1. the information bottleneck size is specified by "inter_channels". for "higher res" it is not as simple as increse model parameters, like people would not just stack a lot of higher-dimensional linear layers, instead they design model structures.  and for the ideal parameters, it needs experimental comparison to find out, i can't just guess a parameter value for you.
2. the loss weight of mel loss and kl divergence.
