### ISSUE TITLE
Question about SR,SPK preprocess in 24khz

### ISSUE THREAD

**Issue by LeMoyenAge** [OlaWod/FreeVC#55]
Should I just use same script as 16k to prerprocess sr, spk pt files?

Or should I change the in dir to vctk-24k and change sr default to 24000?

It would be appreciated if you could give some tip about 24k preprocessing

**Comment by OlaWod** [comment]
use same script as 16k to prerprocess sr, spk pt files
24k preprocessing: use all 16k preprocess steps, and an additional downsample_24k.py step.

**Comment by LeMoyenAge** [comment]
Thank you for your kind answer! It realy helpful.
