### ISSUE TITLE
Robotic noise on audio

### ISSUE THREAD

**Issue by Likkkez** [OlaWod/FreeVC#60]
I'm trying to fine-tune the 24kHZ model but it seems that the more I train it the worse it becomes. Here's how the audio sounds now:

https://user-images.githubusercontent.com/44336181/218494307-d3b12ac7-6870-407d-a12f-a4e43a9b0a26.mp4

I have a custom dataset with a few speakers. Any idea how to get better results? Would adding in the original VCTK dataset to the mix make it better?

**Comment by OlaWod** [comment]
maybe the custom dataset is too small and so leads to overfitting. mix with adding original vctk data may  help.

**Comment by Likkkez** [comment]
> maybe the custom dataset is too small and so leads to overfitting. mix with adding original vctk data may help.

Should I restart finetuning after i add VCTK or just continue from this checkpoint?

**Comment by OlaWod** [comment]
i would prefer restart after add vctk

**Comment by Likkkez** [comment]
> i would prefer restart after add vctk

I added the vctk and trained it more from an earlier checkpoint. I think it cleared up pretty nicely

https://user-images.githubusercontent.com/44336181/219029375-bac274d7-34b3-47ae-8a42-00748d08e170.mp4
