### ISSUE TITLE
Fine-tuning

### ISSUE THREAD

**Issue by Shmuel-Gruel** [OlaWod/FreeVC#8]
Hello, I was wondering if I could try fine-tuning the pretrained model?
I do not have reasonable hardware to train from scratch, unfortunately.
It looks like I would need the pretrained discriminator, if you are able to release it.
Thank you very much, and feel free to let me know if you've already experimented with this.

**Comment by OlaWod** [comment]
Yes. I've uploaded the discriminators to the original sharing link.

**Comment by Shmuel-Gruel** [comment]
Thank you, Li :)
